### ISSUE TITLE
Keep promises from evaluating early

### ISSUE THREAD

**Issue by Thimoteus** [Thimoteus/purescript-promises#1]
The following 

```purescript
prom1 :: forall r. Promise (console :: CONSOLE | r) Unit
prom1 = Console.log "premature evaluation"

prom2 :: forall r. Promise (console :: CONSOLE | r) Unit
prom2 = Console.log "I get evaluated from main"

main :: forall r. Eff (console :: CONSOLE | r) Unit
main = runPromise (\_ -> log "success callback") (\_ -> error "error callback") prom2
```

will print

```
I get evaluated from main
premature evaluation
success callback
```

to the console.

**Comment by hdgarrood** [comment]
I'm not sure if there's any way of addressing this without following the aff-promise approach of using `Eff` wherever you are creating a `Promise`; this also means that you can't give `Promise` a `Monad` instance, since the type of `then` would have to become something like `Promise a -> (a -> Eff eff (Promise a)) -> Eff eff (Promise a)`, which of course no longer matches the type of `bind`. I think, unfortunately, this library is likely to lead beginners astray as it is now; it's probably worth considering pointing them towards `aff` instead, and also `aff-promise` if interop is needed, at least until this issue has been addressed.

**Comment by Thimoteus** [comment]
I solved it by adding a `Deferred` constraint, and allowing it to be discharged only when using `runPromise` to run it in `Eff`.
